adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: skyglass2001@gmail.com
  token: local:jenkinsx/pipelineUser:token
  username: skyglass-jx
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
